version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - mysql
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: terrain_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: terrain_mysql
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: laravel_composer
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["composer"]

networks:
  laravel:

volumes:
  dbdata:
